"""create initial schema

Revision ID: 105ffabed7bc
Revises:
Create Date: 2026-07-29 17:04:10.190748

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "105ffabed7bc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers",
        sa.Column("doi", sa.String(length=512), nullable=True),
        sa.Column("bibliographic_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("publication_year", sa.SmallInteger(), nullable=True),
        sa.Column("venue", sa.String(length=500), nullable=True),
        sa.Column("paper_type", sa.String(length=64), nullable=True),
        sa.Column("official_url", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("citation_text", sa.Text(), nullable=False),
        sa.Column("citation_provider", sa.String(length=64), nullable=False),
        sa.Column("citation_source_url", sa.Text(), nullable=True),
        sa.Column(
            "citation_verified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("jsonb_typeof(authors) = 'array'", name=op.f("ck_papers_authors_array")),
        sa.CheckConstraint(
            "publication_year IS NULL OR publication_year BETWEEN 1000 AND 9999",
            name=op.f("ck_papers_publication_year_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_papers")),
        sa.UniqueConstraint(
            "bibliographic_fingerprint", name=op.f("uq_papers_bibliographic_fingerprint")
        ),
    )
    op.create_index(
        op.f("ix_papers_publication_year"), "papers", ["publication_year"], unique=False
    )
    op.create_index(
        "uq_papers_doi", "papers", ["doi"], unique=True, postgresql_where=sa.text("doi IS NOT NULL")
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("password_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_users_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "research_collections",
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("research_question", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived', 'deleted')",
            name=op.f("ck_research_collections_status"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_research_collections_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_collections")),
    )
    op.create_index(
        op.f("ix_research_collections_owner_user_id"),
        "research_collections",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_collections_status"), "research_collections", ["status"], unique=False
    )
    op.create_table(
        "collection_papers",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_collection_papers_status")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["research_collections.id"],
            name=op.f("fk_collection_papers_collection_id_research_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_collection_papers_paper_id_papers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("collection_id", "paper_id", name=op.f("pk_collection_papers")),
    )
    op.create_index(
        op.f("ix_collection_papers_status"), "collection_papers", ["status"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived', 'deleted')", name=op.f("ck_conversations_status")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["research_collections.id"],
            name=op.f("fk_conversations_collection_id_research_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_conversations_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_collection_id"), "conversations", ["collection_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_owner_user_id"), "conversations", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_status"), "conversations", ["status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("origin_kind", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("access_rights", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "access_rights IN ('user_upload', 'open_access', 'official_allowed')",
            name=op.f("ck_documents_access_rights"),
        ),
        sa.CheckConstraint(
            "origin_kind IN ('user_upload', 'open_access')", name=op.f("ck_documents_origin_kind")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id", "paper_id"],
            ["collection_papers.collection_id", "collection_papers.paper_id"],
            name=op.f("fk_documents_collection_id_collection_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("collection_id", "sha256", name="collection_sha256"),
        sa.UniqueConstraint("object_key", name=op.f("uq_documents_object_key")),
    )
    op.create_index(
        op.f("ix_documents_collection_id"), "documents", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_documents_paper_id"), "documents", ["paper_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system')", name=op.f("ck_messages_role")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'streaming', 'completed', 'failed')",
            name=op.f("ck_messages_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_role"), "messages", ["role"], unique=False)
    op.create_index(op.f("ix_messages_status"), "messages", ["status"], unique=False)
    op.create_table(
        "ingestion_runs",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("arq_job_id", sa.String(length=128), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("parser_name", sa.String(length=128), nullable=True),
        sa.Column("parser_version", sa.String(length=128), nullable=True),
        sa.Column("chunking_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "statistics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempt_no", sa.SmallInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "stage IN ('parse', 'chunk', 'embed', 'index')", name=op.f("ck_ingestion_runs_stage")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_ingestion_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_ingestion_runs_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
        sa.UniqueConstraint("arq_job_id", name=op.f("uq_ingestion_runs_arq_job_id")),
        sa.UniqueConstraint(
            "document_id", "pipeline_version", "attempt_no", name="document_pipeline_attempt"
        ),
    )
    op.create_index(
        op.f("ix_ingestion_runs_document_id"), "ingestion_runs", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_ingestion_runs_stage"), "ingestion_runs", ["stage"], unique=False)
    op.create_index(op.f("ix_ingestion_runs_status"), "ingestion_runs", ["status"], unique=False)
    op.create_table(
        "research_runs",
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("input_message_id", sa.UUID(), nullable=False),
        sa.Column("output_message_id", sa.UUID(), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("langgraph_thread_id", sa.String(length=128), nullable=True),
        sa.Column("model_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "retrieval_trace",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "mode IN ('single_rag', 'multi_agent', 'research_note')",
            name=op.f("ck_research_runs_mode"),
        ),
        sa.CheckConstraint(
            "status IN "
            "('queued', 'running', 'awaiting_clarification', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_research_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["research_collections.id"],
            name=op.f("fk_research_runs_collection_id_research_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["input_message_id"],
            ["messages.id"],
            name=op.f("fk_research_runs_input_message_id_messages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["output_message_id"],
            ["messages.id"],
            name=op.f("fk_research_runs_output_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
        sa.UniqueConstraint("input_message_id", name=op.f("uq_research_runs_input_message_id")),
        sa.UniqueConstraint(
            "langgraph_thread_id", name=op.f("uq_research_runs_langgraph_thread_id")
        ),
    )
    op.create_index(
        op.f("ix_research_runs_collection_id"), "research_runs", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_research_runs_mode"), "research_runs", ["mode"], unique=False)
    op.create_index(op.f("ix_research_runs_status"), "research_runs", ["status"], unique=False)
    op.create_table(
        "document_chunks",
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("parent_chunk_id", sa.UUID(), nullable=True),
        sa.Column("root_chunk_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("section_path", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "locator",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("level BETWEEN 1 AND 3", name=op.f("ck_document_chunks_level_range")),
        sa.CheckConstraint(
            "page_start IS NULL OR page_end IS NULL OR page_start <= page_end",
            name=op.f("ck_document_chunks_page_range"),
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_document_chunks_ingestion_run_id_ingestion_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_document_chunks_parent_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["root_chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_document_chunks_root_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("ingestion_run_id", "ordinal", name="ingestion_run_ordinal"),
    )
    op.create_index(
        op.f("ix_document_chunks_content_sha256"),
        "document_chunks",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_ingestion_run_id"),
        "document_chunks",
        ["ingestion_run_id"],
        unique=False,
    )
    op.create_index(op.f("ix_document_chunks_level"), "document_chunks", ["level"], unique=False)
    op.create_index(
        op.f("ix_document_chunks_parent_chunk_id"),
        "document_chunks",
        ["parent_chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_root_chunk_id"), "document_chunks", ["root_chunk_id"], unique=False
    )
    op.create_table(
        "research_evidences",
        sa.Column("research_run_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("selection_stage", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("vector_score", sa.Float(), nullable=True),
        sa.Column("rrf_score", sa.Float(), nullable=True),
        sa.Column("rerank_score", sa.Float(), nullable=True),
        sa.Column("is_cited", sa.Boolean(), nullable=False),
        sa.Column("citation_excerpt", sa.Text(), nullable=True),
        sa.Column("locator_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "selection_stage IN ('vector', 'rrf', 'rerank', 'final_citation')",
            name=op.f("ck_research_evidences_selection_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_research_evidences_chunk_id_document_chunks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["research_run_id"],
            ["research_runs.id"],
            name=op.f("fk_research_evidences_research_run_id_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_evidences")),
    )
    op.create_index(
        op.f("ix_research_evidences_chunk_id"), "research_evidences", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_evidences_is_cited"), "research_evidences", ["is_cited"], unique=False
    )
    op.create_index(
        op.f("ix_research_evidences_research_run_id"),
        "research_evidences",
        ["research_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_evidences_selection_stage"),
        "research_evidences",
        ["selection_stage"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_evidences_selection_stage"), table_name="research_evidences")
    op.drop_index(op.f("ix_research_evidences_research_run_id"), table_name="research_evidences")
    op.drop_index(op.f("ix_research_evidences_is_cited"), table_name="research_evidences")
    op.drop_index(op.f("ix_research_evidences_chunk_id"), table_name="research_evidences")
    op.drop_table("research_evidences")
    op.drop_index(op.f("ix_document_chunks_root_chunk_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_parent_chunk_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_level"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_ingestion_run_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_content_sha256"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_research_runs_status"), table_name="research_runs")
    op.drop_index(op.f("ix_research_runs_mode"), table_name="research_runs")
    op.drop_index(op.f("ix_research_runs_collection_id"), table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_index(op.f("ix_ingestion_runs_status"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_stage"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_document_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_messages_status"), table_name="messages")
    op.drop_index(op.f("ix_messages_role"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_documents_paper_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_collection_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_owner_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_collection_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_collection_papers_status"), table_name="collection_papers")
    op.drop_table("collection_papers")
    op.drop_index(op.f("ix_research_collections_status"), table_name="research_collections")
    op.drop_index(op.f("ix_research_collections_owner_user_id"), table_name="research_collections")
    op.drop_table("research_collections")
    op.drop_index(
        "uq_users_email_lower", table_name="users", postgresql_where=sa.text("email IS NOT NULL")
    )
    op.drop_table("users")
    op.drop_index("uq_papers_doi", table_name="papers", postgresql_where=sa.text("doi IS NOT NULL"))
    op.drop_index(op.f("ix_papers_publication_year"), table_name="papers")
    op.drop_table("papers")
    # ### end Alembic commands ###
